# Generated by Django 4.2.7 on 2024-01-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
