# Generated by Django 4.2.7 on 2024-01-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_remove_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
