# Generated by Django 4.2.7 on 2024-01-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default=0, max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, default=0, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default=0, max_length=100, verbose_name='Başlık'),
        ),
    ]
