# Generated by Django 4.2.7 on 2024-01-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_alter_category_title_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldprice',
            field=models.FloatField(default=0, verbose_name='Eski Fiyat'),
        ),
    ]
