# Generated by Django 5.0.2 on 2024-02-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saglik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='saglik', verbose_name='Resim')),
                ('title', models.CharField(max_length=150, verbose_name='Baslık')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
    ]
