# Generated by Django 5.0.2 on 2024-02-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0013_sepet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepet',
            name='adet',
            field=models.IntegerField(default=1, verbose_name='Adet'),
        ),
    ]
