# Generated by Django 5.0.2 on 2024-02-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermy',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usermy',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='usermy',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='usermy',
            name='user',
        ),
    ]
