# Generated by Django 5.0.2 on 2024-02-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_alter_usermy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermy',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='usermy',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
    ]
